spec-version:        0.36.0

name:                haskell-logo
version:             0.2.0.0
github:              "mpilgrem/haskell-logo"
license:             BSD-3-Clause
author:              "Mike Pilgrem"
maintainer:          "public@pilgrem.com"
copyright:           "Copyright 2025 Mike Pilgrem"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Test

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mpilgrem/haskell-logo#readme>

dependencies:
- base >= 4.7 && < 5
- diagrams-lib
- diagrams-svg

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  haskell-logo:
    main:                Main.hs
    source-dirs:         app-haskell-logo
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-logo
  stack-logo:
    main:                Main.hs
    source-dirs:         app-stack-logo
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-logo
